name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  msix:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#msix_config:
  #display_name: MyApp
  #publisher_name: MyName
  #identity_name: MyCompany.MySuite.MyApp
  #msix_version: 1.0.0.0
  #certificate_path: C:/<PathToCertificate>/<MyCertificate.pfx>
  #certificate_password: 1234 (require if using .pfx certificate)
  #certificate_subject: CN=MyName
  #logo_path: C:\<PathToIcon>\<Logo.png>
  #start_menu_icon_path: C:\<PathToIcon>\<Icon.png>
  #tile_icon_path: C:\<PathToIcon>\<Icon.png>
  #icons_background_color: transparent
  #architecture: x64
  #capabilities: 'documentsLibrary,internetClient,location,microphone,webcam'