name: msix
description: A command-line tool that create Msix installer from your flutter windows-build files.
version: 3.0.0-dev.1
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Msix
        pluginClass: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  yaml: ^3.1.0
  path: ^1.8.0
  package_config: ^2.0.2
  image: ^3.1.0
  cli_util: ^0.3.5
  cli_dialog: ^0.5.0
  
dev_dependencies: 
  test: ^1.20.1
