name: msix
description: Create Msix installer for flutter windows-build files.
version: 0.0.7
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Msix
        pluginClass: none

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  yaml: ^2.2.1
  ansicolor: ^1.0.5