name: msix
description: Create and sign Msix installer for flutter windows-build files.
version: 0.1.6
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Msix
        pluginClass: none

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ^1.20.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  yaml: ^2.2.1
  ansicolor: ^1.0.5
  args: ^1.6.0